from __future__ import annotations

import argparse
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Callable, Sequence

import psycopg

from . import __version__
from .config import Settings, load_config, resolve_dsn
from .db import (
    connection,
    drop_replication_slot,
    fetch_cluster_identity,
    fetch_slot,
    fetch_slots,
)
from .errors import SlotLeaseError
from .models import ClusterIdentity, format_timestamp
from .plan import (
    build_plan,
    load_plan,
    verify_cluster,
    verify_confirmation,
    verify_policy,
    verify_snapshot,
    write_plan,
)
from .policy import Evaluation, evaluate_slots
from .units import human_bytes, human_duration, parse_duration


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="slotlease",
        description="Inspect and safely retire abandoned PostgreSQL logical replication slots.",
    )
    parser.add_argument(
        "--config",
        default=os.environ.get("SLOTLEASE_CONFIG", "slotlease.yaml"),
        help="YAML policy file (default: SLOTLEASE_CONFIG or slotlease.yaml)",
    )
    parser.add_argument(
        "--dsn",
        help="PostgreSQL DSN (overrides SLOTLEASE_DSN and database.dsn)",
    )
    parser.add_argument("--version", action="version", version=f"%(prog)s {__version__}")

    commands = parser.add_subparsers(dest="command", required=True)

    scan = commands.add_parser("scan", help="read-only inventory and policy evaluation")
    scan.add_argument("--format", choices=("table", "json"), default="table")
    scan.set_defaults(handler=_command_scan)

    plan = commands.add_parser("plan", help="write an integrity-protected drop plan")
    plan.add_argument("--output", default="slotlease-plan.json", help="JSON plan path")
    plan.add_argument(
        "--expires-in",
        help="override plan expiry, for example 15m (default: plan.expires_in)",
    )
    plan.set_defaults(handler=_command_plan)

    apply = commands.add_parser("apply", help="revalidate and apply an approved plan")
    apply.add_argument("--plan", required=True, help="JSON plan generated by `slotlease plan`")
    apply.add_argument(
        "--confirm",
        required=True,
        metavar="PLAN_ID",
        help="exact plan_id, proving explicit operator approval",
    )
    apply.set_defaults(handler=_command_apply)
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    try:
        settings = load_config(args.config)
        dsn = resolve_dsn(settings, args.dsn)
        handler: Callable[[argparse.Namespace, Settings, str], int] = args.handler
        return handler(args, settings, dsn)
    except SlotLeaseError as exc:
        print(f"slotlease: error: {exc}", file=sys.stderr)
        return 2
    except psycopg.Error as exc:
        message = getattr(exc.diag, "message_primary", None) or str(exc)
        sqlstate = f" [{exc.sqlstate}]" if exc.sqlstate else ""
        print(f"slotlease: database error{sqlstate}: {message}", file=sys.stderr)
        return 3


def _command_scan(args: argparse.Namespace, settings: Settings, dsn: str) -> int:
    now = _now()
    with connection(dsn) as conn:
        cluster = fetch_cluster_identity(conn)
        evaluations = evaluate_slots(fetch_slots(conn), settings.slots, now)

    if args.format == "json":
        document = _scan_document(cluster, evaluations, now)
        print(json.dumps(document, ensure_ascii=False, indent=2, sort_keys=True))
    else:
        _print_scan_table(evaluations, now)
    return 0


def _command_plan(args: argparse.Namespace, settings: Settings, dsn: str) -> int:
    now = _now()
    expires_in = (
        parse_duration(args.expires_in, field="--expires-in")
        if args.expires_in is not None
        else settings.plan_expires_in
    )
    if expires_in.total_seconds() <= 0:
        from .errors import ConfigError

        raise ConfigError("--expires-in must be greater than zero")

    with connection(dsn) as conn:
        cluster = fetch_cluster_identity(conn)
        evaluations = evaluate_slots(fetch_slots(conn), settings.slots, now)

    plan = build_plan(evaluations, cluster, now=now, expires_in=expires_in)
    output = Path(args.output)
    write_plan(output, plan)
    print(f"Plan written: {output}")
    print(f"Plan ID: {plan['plan_id']}")
    print(f"Actions: {len(plan['actions'])}")
    print(f"Expires: {plan['expires_at']}")
    print("Apply with:")
    print(
        f"  slotlease --config {args.config} apply --plan {output} "
        f"--confirm {plan['plan_id']}"
    )
    return 0


def _command_apply(args: argparse.Namespace, settings: Settings, dsn: str) -> int:
    now = _now()
    plan = load_plan(args.plan, now=now)
    verify_confirmation(plan, args.confirm)

    actions = plan["actions"]
    for action in actions:
        verify_policy(action, settings)

    with connection(dsn) as conn:
        verify_cluster(plan, fetch_cluster_identity(conn))

        # Preflight the complete plan before the first destructive operation.
        for action in actions:
            verify_snapshot(action, fetch_slot(conn, action["slot_name"]))
        print(f"Preflight OK: {len(actions)} action(s) match the approved plan")

        dropped = 0
        for action in actions:
            slot_name = action["slot_name"]
            # Minimise the TOCTOU window. PostgreSQL itself also refuses to drop
            # an active slot if a consumer connects after this second check.
            verify_snapshot(action, fetch_slot(conn, slot_name))
            drop_replication_slot(conn, slot_name)
            dropped += 1
            print(f"APPLIED drop_replication_slot {slot_name}")

    print(f"Summary: {dropped} applied, 0 skipped, 0 failed")
    return 0


def _scan_document(
    cluster: ClusterIdentity,
    evaluations: list[Evaluation],
    now: datetime,
) -> dict[str, Any]:
    return {
        "generated_at": format_timestamp(now),
        "cluster": cluster.to_dict(),
        "slots": [evaluation.to_report_dict(now) for evaluation in evaluations],
    }


def _print_scan_table(evaluations: list[Evaluation], now: datetime) -> None:
    if not evaluations:
        print("No replication slots found.")
        return

    headings = (
        "SLOT",
        "TYPE",
        "ACTIVE",
        "INACTIVE",
        "RETAINED WAL",
        "STATUS",
        "OWNER",
        "PLAN",
        "REASONS / BLOCKERS",
    )
    rows: list[tuple[str, ...]] = []
    for evaluation in evaluations:
        snapshot = evaluation.snapshot
        rows.append(
            (
                snapshot.slot_name,
                snapshot.slot_type,
                "yes" if snapshot.active else "no",
                human_duration(snapshot.inactive_for(now)),
                human_bytes(snapshot.retained_wal_bytes),
                evaluation.status,
                evaluation.policy.owner if evaluation.policy else "-",
                "drop" if evaluation.eligible_for_plan else "-",
                _format_findings(evaluation),
            )
        )
    widths = [
        max(len(headings[index]), *(len(row[index]) for row in rows))
        for index in range(len(headings))
    ]
    print(_format_row(headings, widths))
    print(_format_row(tuple("-" * width for width in widths), widths))
    for row in rows:
        print(_format_row(row, widths))


def _format_row(row: tuple[str, ...], widths: list[int]) -> str:
    return "  ".join(value.ljust(widths[index]) for index, value in enumerate(row)).rstrip()


def _format_findings(evaluation: Evaluation) -> str:
    findings = [*evaluation.reasons]
    findings.extend(f"blocked:{blocker}" for blocker in evaluation.blockers)
    return ",".join(findings) if findings else "-"


def _now() -> datetime:
    # Kept behind a function so CLI tests can patch one deterministic clock point.
    return datetime.now(timezone.utc)


if __name__ == "__main__":
    raise SystemExit(main())
